[package]
name = "starkflow_contracts"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.2"
# braavos = { git = "https://github.com/myBraavos/braavos-account-cairo.git", tag="v1.1.0"}

[[target.starknet-contract]]
sierra = true
casm = true
